import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import SideBar from "@/app/components/layout/SideBar";
import Footer from "../components/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="pt-BR">
        <body
          className={`${poppins.className} antialiased`}
        >
          <Toaster richColors/>
          <div className="grid lg:grid-cols-[17rem_1fr] text-[#F4F4F5]">
            <div>
              <SideBar />
            </div>
            <div className="flex flex-col bg-neutral-800 min-h-screen w-full max-w-6xl mx-auto px-2">
              {children}
              <Footer />
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
